# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

common: &common
  smtp_address: <%= ENV.fetch("SMTP_ADDRESS") %>
  smtp_port: <%= ENV.fetch("SMTP_PORT") %>
  smtp_username: <%= ENV.fetch("SMTP_USERNAME") %>
  smtp_password: <%= ENV.fetch("SMTP_PASSWORD") %>
  smtp_domain: <%= ENV.fetch("SMTP_DOMAIN") %>

  google_maps_api_key: <%= ENV.fetch("GOOGLE_MAPS_API_KEY") %>

  streak_api_key: <%= ENV.fetch("STREAK_API_KEY") %>
  streak_club_pipeline_key: <%= ENV.fetch("STREAK_CLUB_PIPELINE_KEY") %>
  streak_club_applications_pipeline_key: <%= ENV.fetch("STREAK_CLUB_APPLICATIONS_PIPELINE_KEY") %>
  streak_leader_pipeline_key: <%= ENV.fetch("STREAK_LEADER_PIPELINE_KEY") %>
  streak_letter_pipeline_key: <%= ENV.fetch("STREAK_LETTER_PIPELINE_KEY") %>
  streak_fundraising_pipeline_key: <%= ENV.fetch("STREAK_FUNDRAISING_PIPELINE_KEY") %>

  cloud9_username: <%= ENV.fetch("CLOUD9_USERNAME") %>
  cloud9_password: <%= ENV.fetch("CLOUD9_PASSWORD") %>
  cloud9_team_name: <%= ENV.fetch("CLOUD9_TEAM_NAME") %>

  segment_write_key: <%= ENV.fetch("SEGMENT_WRITE_KEY") %>

  # For Athul
  athul_auth_token: <%= ENV.fetch("ATHUL_AUTH_TOKEN") %>

  # For outreach:teacher_emails tasks
  streak_outreach_school_pipeline_key: <%= ENV.fetch("STREAK_OUTREACH_SCHOOL_PIPELINE_KEY") %>
  streak_outreach_teacher_pipeline_key: <%= ENV.fetch("STREAK_OUTREACH_TEACHER_PIPELINE_KEY") %>

  # For RecordSlackStatsJob
  slack_admin_email: <%= ENV.fetch("SLACK_ADMIN_EMAIL") %>
  slack_admin_password: <%= ENV.fetch("SLACK_ADMIN_PASSWORD") %>

  # This is quoted because Slack's client ID has a period in it.
  slack_client_id: "<%= ENV.fetch('SLACK_CLIENT_ID') %>"
  slack_client_secret: <%= ENV.fetch("SLACK_CLIENT_SECRET") %>
  default_slack_team_id: <%= ENV.fetch("DEFAULT_SLACK_TEAM_ID") %>

  # For HackbotTeamSetup spec helper.
  #
  # This must be a valid bot access token. See HackbotTeamSetup for more
  # details.
  spec_slack_access_token: <%= ENV["SPEC_SLACK_ACCESS_TOKEN"] %>

  tech_domain_redemption_secret_code: <%= ENV.fetch("TECH_DOMAIN_REDEMPTION_SECRET_CODE") %>

  guggy_api_key: <%= ENV.fetch("GUGGY_API_KEY") %>

  default_streak_task_assignee: <%= ENV.fetch("DEFAULT_STREAK_TASK_ASSIGNEE") %>

  hackbot_mirror_channel_id: <%= ENV.fetch("HACKBOT_MIRROR_CHANNEL_ID") %>
  hackbot_admins: <%= ENV.fetch("HACKBOT_ADMINS").split(",") %>

  # This is for the DemoCheckIn interaction
  streak_demo_user_box_key: <%= ENV.fetch("STREAK_DEMO_USER_BOX_KEY") %>

  github_bot_access_token: <%= ENV.fetch("GITHUB_BOT_ACCESS_TOKEN") %>

  slack_admin_access_token: <%= ENV.fetch("SLACK_ADMIN_ACCESS_TOKEN") %>

  repo_files_root: vendor/hackclub
  stripe_publishable_key: <%= ENV.fetch("STRIPE_PUBLISHABLE_KEY") %>
  stripe_secret_key: <%= ENV.fetch("STRIPE_SECRET_KEY") %>

  channels_to_clear: <%= ENV.fetch("CHANNELS_TO_CLEAR") %>

development:
  <<: *common
  secret_key_base: 6d02f9126a44347e07442fddf774b6a434a85b86e23629eab947c9c101b8aa878ad8fe5dadba26a3341f1a16f480068ae5234861cb7b913f526a0e96a21fcc7d

test:
  <<: *common
  secret_key_base: 7690707d9315088014cce0ab1384a190c8d12cabc0a25d54ec937ee961c0fea23794db571bd4ba3e3ca3e6b9d1229ddbced73015510ddf1b8dbe0839881f4011

  workshop_files_root: spec/test_workshops

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *common
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
